approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
