approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

nodeLinker: pnp

npmMinimalAgeGate: 3d

packageExtensions:
  "bootstrap@*":
    dependencies:
      "@popperjs/core": "*"
      jquery: "*"
  "@overleaf/settings@*":
    peerDependencies:
      "@overleaf/logger": "*"
  "mongodb@*":
    peerDependencies:
      aws4: "*"
  "bunyan@*":
    peerDependencies:
      source-map-support: "*"
  "mocha-multi-reporters@*":
    peerDependencies:
      mocha-junit-reporter: "*"
  "mongodb-legacy@*":
    peerDependencies:
      mongodb: "*"
  "knex@*":
    dependencies:
      pg-query-stream: "*"
  "zod-validation-error@*":
    peerDependencies:
      zod: "*"
  "@vitejs/plugin-react@*":
    peerDependencies:
      vite: "*"
  "@babel/preset-env@*":
    peerDependencies:
      core-js: "*"
  "express@*":
    dependencies:
      pug: "*"
  "postcss-loader@*":
    peerDependencies:
      autoprefixer: "*"
      tailwindcss: "*"
  "@ai-sdk/gateway@*":
    peerDependencies:
      zod: "*"
  "@ai-sdk/provider-utils@*":
    peerDependencies:
      zod: "*"
  "ai@*":
    peerDependencies:
      zod: "*"
  "@uppy/react@*":
    peerDependencies:
      "@uppy/status-bar": "*"
  "inversify@*":
    dependencies:
      reflect-metadata: "*"
  "sinon-mongoose@*":
    dependencies:
      mongoose: "*"
  "react-linkify@*":
    peerDependencies:
      react: "*"
  "debug@*":
    peerDependenciesMeta:
      supports-color:
        optional: true

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
