#!/bin/sh

cd /overleaf/services/project-history && node scripts/flush_all.js >> /var/log/sharelatex/project-history.log 2>&1

EXIT_CODE="$?"
if [ $EXIT_CODE -ne 0 ]
then
  echo "project-history/scripts/flush_all.js failed with exit code $EXIT_CODE"
fi

exit 0
