#!/bin/sh

cd /overleaf/services/document-updater && node scripts/flush_all.js >> /var/log/sharelatex/document-updater.log 2>&1

EXIT_CODE="$?"
if [ $EXIT_CODE -ne 0 ]
then
  echo "document-updater/scripts/flush_all.js failed with exit code $EXIT_CODE"
fi

exit 0
