#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - clsi"
    NODE_PARAMS="--inspect=0.0.0.0:30130"
fi

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /var/www/sharelatex/clsi/app.js >> /var/log/sharelatex/clsi.log 2>&1
