#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - track-changes"
    NODE_PARAMS="--inspect=0.0.0.0:30150"
fi

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /var/www/sharelatex/track-changes/app.js >> /var/log/sharelatex/track-changes.log 2>&1
