#!/bin/bash

source /etc/overleaf/env.sh
export LISTEN_ADDRESS=127.0.0.1
export FILESTORE_PORT=3009

exec /sbin/setuser www-data /usr/bin/node /overleaf/services/filestore/app.js >> /var/log/overleaf/filestore.log 2>&1
