#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - tags"
    NODE_PARAMS="--inspect=0.0.0.0:30120"
fi

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /var/www/sharelatex/tags/app.js >> /var/log/sharelatex/tags.log 2>&1
