#!/bin/bash

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - chat"
    NODE_PARAMS="--inspect=0.0.0.0:30100"
fi

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS  /var/www/sharelatex/chat/app.js >> /var/log/sharelatex/chat.log 2>&1
