BUILD_DIR_NAME ?= web
MODULE_NAME := $(notdir $(shell pwd))
MODULE_DIR := modules/$(MODULE_NAME)
PROJECT_NAME = web

export SHARELATEX_CONFIG = /app/$(MODULE_DIR)/test/acceptance/config/settings.test.js
export BASE_CONFIG ?= /app/test/acceptance/config/settings.test.saas.js

CFG_SAAS=/app/test/acceptance/config/settings.test.saas.js
CFG_SERVER_CE=/app/test/acceptance/config/settings.test.server-ce.js
CFG_SERVER_PRO=/app/test/acceptance/config/settings.test.server-pro.js

DOCKER_COMPOSE_FLAGS ?= -f docker-compose.yml --log-level ERROR
DOCKER_COMPOSE := cd ../../ && \
	MODULE_DIR=$(MODULE_DIR) \
	BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH_NAME=$(BRANCH_NAME) \
	PROJECT_NAME=$(PROJECT_NAME) \
	MOCHA_GREP=${MOCHA_GREP} \
	docker-compose ${DOCKER_COMPOSE_FLAGS}

DOCKER_COMPOSE_TEST_ACCEPTANCE := \
	export COMPOSE_PROJECT_NAME=acceptance_test_$(BUILD_DIR_NAME)_$(MODULE_NAME) \
	&& $(DOCKER_COMPOSE)

DOCKER_COMPOSE_TEST_UNIT := \
	export COMPOSE_PROJECT_NAME=unit_test_$(BUILD_DIR_NAME)_$(MODULE_NAME) \
	&& $(DOCKER_COMPOSE)

ifeq (,$(wildcard test/unit))
test_unit:

else
test_unit:
	${DOCKER_COMPOSE_TEST_UNIT} run --rm test_unit npm -q run test:unit:run_dir -- ${MOCHA_ARGS} $(MODULE_DIR)/test/unit/src
	${DOCKER_COMPOSE_TEST_UNIT} down

endif

ALL_TEST_ACCEPTANCE_VARIANTS := \
  test_acceptance \
  test_acceptance_saas \
  test_acceptance_server_ce \
  test_acceptance_server_pro \

ifeq (,$(wildcard test/acceptance))
$(ALL_TEST_ACCEPTANCE_VARIANTS):
test_acceptance_merged_inner:
clean_test_acceptance:

else
test_acceptance_saas: export BASE_CONFIG = $(CFG_SAAS)
test_acceptance_server_ce: export BASE_CONFIG = $(CFG_SERVER_CE)
test_acceptance_server_pro: export BASE_CONFIG = $(CFG_SERVER_PRO)

$(ALL_TEST_ACCEPTANCE_VARIANTS):
	$(MAKE) --no-print-directory clean_test_acceptance
	${DOCKER_COMPOSE_TEST_ACCEPTANCE} run --rm test_acceptance npm -q run test:acceptance:run_dir -- ${MOCHA_ARGS} $(MODULE_DIR)/test/acceptance/src
	$(MAKE) --no-print-directory clean_test_acceptance

test_acceptance_merged_inner:
	cd ../../ && \
			npm -q run test:acceptance:run_dir -- ${MOCHA_ARGS} $(MODULE_DIR)/test/acceptance/src

clean_test_acceptance:
	${DOCKER_COMPOSE_TEST_ACCEPTANCE} down -v -t 0

endif
