#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - contacts"
    NODE_PARAMS="--inspect=0.0.0.0:30360"
fi

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /var/www/sharelatex/contacts/app.js >> /var/log/sharelatex/contacts.log 2>&1
