#!/bin/bash

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - document updater"
    NODE_PARAMS="--inspect=0.0.0.0:30030"
fi

source /etc/overleaf/env.sh
export LISTEN_ADDRESS=127.0.0.1

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /overleaf/services/document-updater/app.js >> /var/log/overleaf/document-updater.log 2>&1
