export type AdminCapability =
  | 'clear-saml-data'
  | 'clear-session'
  | 'create-recurly-account'
  | 'create-subscription'
  | 'modify-feature-override'
  | 'modify-login-status'
  | 'manage-survey'
  | 'modify-user-email'
  | 'modify-user-name'
  | 'view-audit-log'
  | 'view-project'
  | 'view-session'
  | 'view-script-log'
  | 'view-user-additional-info'

export type AdminRole =
  | 'engagement'
  | 'engineering'
  | 'finance'
  | 'product'
  | 'sales'
  | 'support'
  | 'support_tier_1'
