export type IconElementMaterial =
  | 'add_notes'
  | 'assured_workload'
  | 'biotech'
  | 'book_5'
  | 'draw'
  | 'edit_document'
  | 'edit_note'
  | 'function'
  | 'groups'
  | 'live_tv'
  | 'local_library'
  | 'lock'
  | 'picture_as_pdf'
  | 'preview'
  | 'school'
  | 'security'
  | 'verified_user'
  | 'workspace_premium'

export type IconElementSticker =
  | 'sticker | arrow | grey | large'
  | 'sticker | books | pink'
  | 'sticker | books | yellow'
  | 'sticker | cog-pen | grey'
  | 'sticker | collaborate | purple'
  | 'sticker | collaborate | yellow'
  | 'sticker | data | grey'
  | 'sticker | formatting | green'
  | 'sticker | house-tree | grey | large'
  | 'sticker | hub | tangerine'
  | 'sticker | lock | grey | medium'
  | 'sticker | lightning | yellow'
  | 'sticker | overleaf | green | medium'
  | 'sticker | pen | purple'
  | 'sticker | pen | tangerine'
  | 'sticker | pi | tangerine'
  | 'sticker | rocket | yellow | medium'
  | 'sticker | support | tangerine'
  | 'sticker | support | yellow'

export type IconElement = IconElementMaterial | IconElementSticker
export type IconStyle = 'Green circle' | 'Large purple text' | 'Default'
