export type IconElementMaterial =
  | 'add_notes'
  | 'assured_workload'
  | 'biotech'
  | 'book_5'
  | 'draw'
  | 'edit_document'
  | 'edit_note'
  | 'function'
  | 'groups'
  | 'live_tv'
  | 'local_library'
  | 'lock'
  | 'picture_as_pdf'
  | 'preview'
  | 'school'
  | 'security'
  | 'verified_user'
  | 'workspace_premium'

export type IconElementSticker =
  | 'arrow_sticker_grey'
  | 'books_sticker_yellow'
  | 'cog-pen_sticker_grey'
  | 'collaborate_sticker_purple'
  | 'collaborate_sticker_yellow'
  | 'data_sticker_grey'
  | 'formatting_sticker_green'
  | 'house-tree_sticker_grey'
  | 'hub_sticker_tangerine'
  | 'lock_sticker_grey'
  | 'overleaf_sticker_green'
  | 'pen_sticker_purple'
  | 'pen_sticker_tangerine'
  | 'pi_sticker_tangerine'
  | 'support_sticker_tangerine'
  | 'support_sticker_yellow'

export type IconElement = IconElementMaterial | IconElementSticker
export type IconStyle = 'Green circle' | 'Large purple text' | 'Default'
