apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    {{- include "overleaf.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
