apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    {{- include "overleaf.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
