apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overleaf-data
  labels:
    app: overleaf
    {{- include "overleaf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.overleaf.persistence.size }}
