apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIICy770MnfOrQwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA1MzEyMTI2NTRaFw0zNjA1MjgyMTMxNTRaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCfPa4zkpVWrXryR7J0Uu/sXTeZC4m7MBepTWiiJ48GCICi4rHvFOENBUdo
      beNIP3nv9Moyblna787Tobs0qMuTu/Sxpl4riR0+4g8cMsxbcc9p9+8jo4g5sbyE
      e+GBl23P2rZWesURQoh67f/l/l28atOHVvvQKKgQ28pZsCJ8v09KPGCvojOICMZV
      cgbtpKlV5GYU1fy72Kg1AUeVqXw5nRvNGXI1isMi01aAhSEzNjRpvfbVbk2YYkrJ
      eN0TzjD0AQYSGZRkRFtUyOCvT9li797G/oLDvfdVajFFjO4I4UU4eFWvENeMj++D
      8jpMSc47rfMzN+KftqBWjtM0RczRAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTgtRDcOUxvlZVWm4j7FKRWarWByjAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCc6faB9Uyv
      NDVDDD3TUQncahH5YKCcGKX2b0vw38LV3sJJ4ynRemE0JQPEf27ywJW44hIATFRx
      fhG6eUXxkd8VTfeshNt6FzVvexkiMakF6WZg6c0tjfrmncs6lqkb2K9jYMaudk7f
      wvYBpX1ckdPkjyBkYMmbpnDEOOE/tu0XkiGn2e/DtU0oEx1ShQFN7iTQmhq0ABFm
      aIXzEw2CI9gZJOSLh2Ob6GXH2x/RN0BpFsoj+rnDqh7fOKXRnPLLgX9AUOwNjbqf
      AyWERb+6o9gsYrFKMJ58sjM8U8Fx1PUVY89sfAQTRbkfPtQy2ufjHuKBog3inWdU
      x5eD6greM+9x
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-05-31T21:33:22Z"
    name: kube-root-ca.crt
    namespace: overleaf
    resourceVersion: "843"
    uid: a3eb92ac-b555-4b9d-978d-0b9f165ec031
- apiVersion: v1
  data:
    mongodb-init-replica-set.js: |
      rs.initiate({ _id: 'overleaf', members: [{ _id: 0, host: 'mongo:27017' }] })
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: overleaf:/ConfigMap:overleaf/mongo-init
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"mongodb-init-replica-set.js":"rs.initiate({ _id: 'overleaf', members: [{ _id: 0, host: 'mongo:27017' }] })\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"overleaf:/ConfigMap:overleaf/mongo-init"},"labels":{"app":"mongo","app.kubernetes.io/managed-by":"Helm","helm.sh/chart":"overleaf-0.1.0"},"name":"mongo-init","namespace":"overleaf"}}
    creationTimestamp: "2026-05-31T21:33:22Z"
    labels:
      app: mongo
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: overleaf-0.1.0
    name: mongo-init
    namespace: overleaf
    resourceVersion: "845"
    uid: e20f7740-ad61-4188-b03f-95593b3107b0
- apiVersion: v1
  data:
    EMAIL_CONFIRMATION_DISABLED: "true"
    EXTERNAL_AUTH: none
    OVERLEAF_APP_NAME: kind Overleaf
    OVERLEAF_MONGO_URL: mongodb://mongo/overleaf
    OVERLEAF_PORT_80_TCP: "30080"
    OVERLEAF_PORT_80_TCP_ADDR: "30081"
    OVERLEAF_REDIS_HOST: redis
    OVERLEAF_SERVICE_HOST: overleaf
    REDIS_HOST: redis
    REDIS_PORT: "6379"
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: overleaf:/ConfigMap:overleaf/overleaf-variables
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"EMAIL_CONFIRMATION_DISABLED":"true","EXTERNAL_AUTH":"none","OVERLEAF_APP_NAME":"kind Overleaf","OVERLEAF_MONGO_URL":"mongodb://mongo/overleaf","OVERLEAF_PORT_80_TCP":"30080","OVERLEAF_PORT_80_TCP_ADDR":"30081","OVERLEAF_REDIS_HOST":"redis","OVERLEAF_SERVICE_HOST":"overleaf","REDIS_HOST":"redis","REDIS_PORT":"6379"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"overleaf:/ConfigMap:overleaf/overleaf-variables"},"name":"overleaf-variables","namespace":"overleaf"}}
    creationTimestamp: "2026-05-31T21:33:22Z"
    name: overleaf-variables
    namespace: overleaf
    resourceVersion: "846"
    uid: 328975dc-fec0-425f-9a8c-2ebf4173730d
kind: List
metadata:
  resourceVersion: ""
