name: build and push sharelatex image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lcpu-club/sharelatex

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.title=overleaf
            org.opencontainers.image.description=overleaf
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=ref,event=branch
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare to build
        run: |
          cp ${{ github.workspace }}/server-ce/.dockerignore ${{ github.workspace }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          provenance: false
          build-args: |
            OVERLEAF_BASE=ghcr.io/lcpu-club/sharelatex-base:latest
            MONOREPO_REVISION=${{ github.sha }}
          push: true
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/server-ce/Dockerfile
          #platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=ghcr.io/lcpu-club/sharelatex:latest
            type=registry,ref=ghcr.io/lcpu-club/sharelatex:main
          cache-to: type=inline
